# Generated by Django 5.2.3 on 2025-10-22 04:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_options_alter_product_name_and_more'),
        ('purchases', '0001_initial'),
        ('sales', '0002_alter_sale_options_alter_saleitem_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='purchase',
            options={'ordering': ['-date'], 'verbose_name': 'Compra', 'verbose_name_plural': 'Compras'},
        ),
        migrations.AlterModelOptions(
            name='purchaseitem',
            options={'verbose_name': 'Item da Compra', 'verbose_name_plural': 'Itens das Compras'},
        ),
        migrations.AlterField(
            model_name='purchase',
            name='date',
            field=models.DateTimeField(auto_now_add=True, help_text='Data e hora da criação da compra'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='sale',
            field=models.ForeignKey(help_text='Venda que esta compra está atendendo', on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='sales.sale'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='user',
            field=models.ForeignKey(help_text='Usuário que criou a compra', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='purchaseitem',
            name='product',
            field=models.ForeignKey(help_text='Produto sendo comprado', on_delete=django.db.models.deletion.CASCADE, to='products.product'),
        ),
        migrations.AlterField(
            model_name='purchaseitem',
            name='purchase',
            field=models.ForeignKey(help_text='Compra à qual este item pertence', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='purchases.purchase'),
        ),
        migrations.AlterField(
            model_name='purchaseitem',
            name='quantity',
            field=models.PositiveIntegerField(help_text='Quantidade do produto comprada'),
        ),
    ]
