# Generated by Django 5.2.3 on 2025-10-24 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0003_product_created_at"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Produto",
                "verbose_name_plural": "Produtos",
            },
        ),
    ]
