# Generated by Django 5.2.3 on 2025-10-22 04:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_options_alter_product_name_and_more'),
        ('sales', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sale',
            options={'ordering': ['-date'], 'verbose_name': 'Venda', 'verbose_name_plural': 'Vendas'},
        ),
        migrations.AlterModelOptions(
            name='saleitem',
            options={'verbose_name': 'Item da Venda', 'verbose_name_plural': 'Itens das Vendas'},
        ),
        migrations.AlterField(
            model_name='sale',
            name='date',
            field=models.DateTimeField(auto_now_add=True, help_text='Data e hora da criação da venda'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='user',
            field=models.ForeignKey(help_text='Usuário que criou a venda', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='saleitem',
            name='product',
            field=models.ForeignKey(help_text='Produto sendo vendido', on_delete=django.db.models.deletion.CASCADE, to='products.product'),
        ),
        migrations.AlterField(
            model_name='saleitem',
            name='quantity',
            field=models.PositiveIntegerField(help_text='Quantidade do produto vendida'),
        ),
        migrations.AlterField(
            model_name='saleitem',
            name='sale',
            field=models.ForeignKey(help_text='Venda à qual este item pertence', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='sales.sale'),
        ),
    ]
