# Generated by Django 5.2.3 on 2025-10-22 05:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_options_alter_product_name_and_more'),
        ('sales', '0002_alter_sale_options_alter_saleitem_options_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='saleitem',
            unique_together={('sale', 'product')},
        ),
    ]
